name: Check IP

on:
  push:         # Trigger on push events
  workflow_dispatch:  # Allow manual trigger

jobs:
  get_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get Public IP
        run: curl ipinfo.io
